In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = 5

result = a + b
print(result)

[6 7 8]


In [2]:
# Reshaping an Array

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [4]:
# Flattening an Array

# a) flatten() – returns a copy:


a = np.array([[1, 2], [3, 4]])
flat = a.flatten()
print(flat)


[1 2 3 4]


In [5]:
# b) ravel() – returns a view (no data copied unless needed):


flat_view = a.ravel()


In [6]:
# c) reshape(-1) – also flattens:

flat_reshape = a.reshape(-1)
